AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Relax complexity/size cops to avoid refactors at this stage
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Style/Documentation:
  Enabled: false

# Formatting nuances
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Max: 120
